---
driver:
  name: vagrant

provisioner:
  name: chef_zero

driver_config:
  network:
    - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
    - ["private_network", {ip: "10.11.12.13"}]
  customize:
    memory: 2048
    cpus: 2

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-7.0
    run_list:
      - recipe[yum]
  - name: centos-6.5
    run_list:
      - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[gitlab::default]
    attributes:
